<?php
/**
 * TL_ROOT/system/modules/log_report/languages/de/tl_settings.php 
 * 
 * Contao extension: log_report 2.1.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2012 Marko Cupic, Oberkirch CH 
 * License   : shareware 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['log_report_legend'] = "Log-Report";
$GLOBALS['TL_LANG']['tl_settings']['log_report_activate']['0'] = "Log-Report aktivieren";
$GLOBALS['TL_LANG']['tl_settings']['log_report_recipients']['0'] = "Mail-Empf&auml;nger:";
$GLOBALS['TL_LANG']['tl_settings']['log_report_recipients']['1'] = "Bitte geben Sie eine Komma-separierte Liste mit Email-Adressen an.";
$GLOBALS['TL_LANG']['tl_settings']['log_report_observed_tables']['0'] = "Überwachte Tabellen:";
$GLOBALS['TL_LANG']['tl_settings']['log_report_observed_tables']['1'] = "Wählen Sie die Tabellen, die überwacht werden sollen, aus.";
$GLOBALS['TL_LANG']['tl_settings']['log_report_additional_observed_tables']['0'] = "Zusätzliche zu überwachende Tabellen:";
$GLOBALS['TL_LANG']['tl_settings']['log_report_additional_observed_tables']['1'] = "Erstellen Sie hier eine kommaseparierte Liste mit Tabellennamen, die Sie überwacht haben möchten. (tl_table1,tl_table2,...)";
$GLOBALS['TL_LANG']['tl_settings']['log_report_send_email_when_db_changed']['0'] = "Nur bei Änderungen benachrichtigen";
$GLOBALS['TL_LANG']['tl_settings']['log_report_send_email_when_db_changed']['1'] = "Wenn keine Änderungen vorhanden sind, wird bei aktivierter Checkbox das System den Empfänger nicht benachrichtigen.";
$GLOBALS['TL_LANG']['tl_settings']['log_report_template']['0'] = "Template-Einstellungen:";
$GLOBALS['TL_LANG']['tl_settings']['log_report_template']['1'] = "Wählen Sie ein template aus.";
 
?>
