<?php
/**
 * TL_ROOT/system/modules/log_report/languages/de/default.php 
 * 
 * Contao extension: log_report 2.1.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2012 Marko Cupic, Oberkirch CH 
 * License   : shareware 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['default']['log_report_modifications'] = "Änderungen an";
$GLOBALS['TL_LANG']['default']['log_report_no_modifications_found'] = "Keine Änderungen gefunden!";
$GLOBALS['TL_LANG']['default']['log_report_username'] = "Angemeldeter Benutzer";
$GLOBALS['TL_LANG']['default']['linkToContaoBackendModule'] = "Link ins Contao Backend";
$GLOBALS['TL_LANG']['default']['NEW_ENTRY'] = "Neuer Datenbankeintrag";
$GLOBALS['TL_LANG']['default']['EDIT'] = "Ver&auml;nderter Datenbankeintrag";
$GLOBALS['TL_LANG']['default']['DELETE'] = "Gel&ouml;schter Datenbankeintrag";
?>
