<?php
/**
 * TL_ROOT/system/modules/log_report/languages/de/tl_maintenance.php 
 * 
 * Contao extension: log_report 2.1.0 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2012 Marko Cupic, Oberkirch CH 
 * License   : shareware 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_maintenance_jobs']['log_report']['0'] = "log_report löschen";
$GLOBALS['TL_LANG']['tl_maintenance_jobs']['log_report']['1'] = "Leert die Tabelle tl_log_report. Die Daten werden hierdurch endgültig gelöscht.";
 
?>
